// Generated by gencpp from file lifter_ctr/lifter_mode.msg
// DO NOT EDIT!


#ifndef LIFTER_CTR_MESSAGE_LIFTER_MODE_H
#define LIFTER_CTR_MESSAGE_LIFTER_MODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lifter_ctr
{
template <class ContainerAllocator>
struct lifter_mode_
{
  typedef lifter_mode_<ContainerAllocator> Type;

  lifter_mode_()
    : updown_mode()  {
    }
  lifter_mode_(const ContainerAllocator& _alloc)
    : updown_mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _updown_mode_type;
  _updown_mode_type updown_mode;





  typedef boost::shared_ptr< ::lifter_ctr::lifter_mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lifter_ctr::lifter_mode_<ContainerAllocator> const> ConstPtr;

}; // struct lifter_mode_

typedef ::lifter_ctr::lifter_mode_<std::allocator<void> > lifter_mode;

typedef boost::shared_ptr< ::lifter_ctr::lifter_mode > lifter_modePtr;
typedef boost::shared_ptr< ::lifter_ctr::lifter_mode const> lifter_modeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lifter_ctr::lifter_mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lifter_ctr::lifter_mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lifter_ctr::lifter_mode_<ContainerAllocator1> & lhs, const ::lifter_ctr::lifter_mode_<ContainerAllocator2> & rhs)
{
  return lhs.updown_mode == rhs.updown_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lifter_ctr::lifter_mode_<ContainerAllocator1> & lhs, const ::lifter_ctr::lifter_mode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lifter_ctr

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lifter_ctr::lifter_mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lifter_ctr::lifter_mode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifter_ctr::lifter_mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lifter_ctr::lifter_mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifter_ctr::lifter_mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lifter_ctr::lifter_mode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lifter_ctr::lifter_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7990a6d0129a755d88d46f3f5051aed";
  }

  static const char* value(const ::lifter_ctr::lifter_mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7990a6d0129a755ULL;
  static const uint64_t static_value2 = 0xd88d46f3f5051aedULL;
};

template<class ContainerAllocator>
struct DataType< ::lifter_ctr::lifter_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lifter_ctr/lifter_mode";
  }

  static const char* value(const ::lifter_ctr::lifter_mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lifter_ctr::lifter_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string updown_mode\n"
;
  }

  static const char* value(const ::lifter_ctr::lifter_mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lifter_ctr::lifter_mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.updown_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lifter_mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lifter_ctr::lifter_mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lifter_ctr::lifter_mode_<ContainerAllocator>& v)
  {
    s << indent << "updown_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.updown_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIFTER_CTR_MESSAGE_LIFTER_MODE_H
